-- plugins

require('thijssesc.plugins.blanket')
require('thijssesc.plugins.colorscheme')
require('thijssesc.plugins.column')
require('thijssesc.plugins.comment')
require('thijssesc.plugins.dap')
require('thijssesc.plugins.gitsigns')
require('thijssesc.plugins.harpoon')
require('thijssesc.plugins.indentline')
require('thijssesc.plugins.lsp')
require('thijssesc.plugins.lualine')
require('thijssesc.plugins.neogen')
require('thijssesc.plugins.packer')
require('thijssesc.plugins.telescope')
require('thijssesc.plugins.tree')
require('thijssesc.plugins.treesitter')
