#!/usr/bin/env sh
#
# $XDG_CONFIG_HOME/bash/aliases
#

# Terminal application aliases
alias htop-term='st -n htopterm -e hiop --user $USER'
alias nnn-term='st -n nnnterm -e nnn -CHde'
alias rtorrent-term='st -n rtorrenterm -e rtorrent'
alias spt-term='st -n sptterm -e spt'
alias vim-term='st -n vimterm -e nvim'

# VPN
alias zscaler='/opt/zscaler/bin/ZSTray'

# Other
alias tabbed-surf='tabbed -d -r 2 surf -e "surf" 2>/dev/null'
