#!/usr/bin/env bash
#
# $XDG_CONFIG_HOME/bash/bashrc
#

# shellcheck source=/dev/null

# Prompt fallback
PS1=" \W\[\e[0m\]\[\e[1;37m\] >>\[\e[34m\]> \[\e[0m\] "

# Git completion
. /usr/share/git/completion/git-completion.bash

# nvm support
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
[ -s "$NVM_DIR/nvm.sh" ] && ."$NVM_DIR/nvm.sh"

# Include aliases and functions
[ -f "$XDG_CONFIG_HOME/bash/aliases" ] && \
    . "$XDG_CONFIG_HOME/bash/aliases"
[ -f "$XDG_CONFIG_HOME/bash/functions" ] && \
    . "$XDG_CONFIG_HOME/bash/functions"

# Include shortcuts
[ -f "$XDG_CONFIG_HOME/bash/shortcuts" ] && \
    . "$XDG_CONFIG_HOME/bash/shortcuts"

for al in $(__git_aliases); do
  # shellcheck disable=SC2139,2086
  alias g$al="git $al"

  complete_func=_git_$(__git_aliased_command "$al")
  __function_exists "$complete_func" && __git_complete g"$al" "$complete_func"
done

# Display some info
icy

# Bash options
shopt -s autocd
set   -o vi

# Terminal Aliases
[ -f "$XDG_CONFIG_HOME/bash/taliases" ] && \
    . "$XDG_CONFIG_HOME/bash/taliases"
