#!/usr/bin/env sh
#
# Script to output system information to a 'bar'.
#

# shellcheck source=/dev/null
. ~/.local/scripts/clr

battery() {
    battery=$(acpi)
    status=$(printf '%s' "$battery" | awk -F ':|,' '{print $2}' | sed 's/ //g')
    percentage=$(printf '%s' "$battery" | awk -F ', '  '{print $2}' | sed 's/%//')

    case "$percentage" in
        [0-9]|1[0-9])         color="$(colors 1)"; icon="" ;;
        2[0-9]|3[0-9]|4[0-9]) color="$(colors 3)"; icon="" ;;
        5[0-9]|6[0-9])        color="$(colors 4)"; icon="" ;;
        7[0-9]|8[0-9])        color="$(colors 2)"; icon="" ;;
        *)                    color="$(colors 7)"; icon="" ;;
    esac
    case "$status" in
        "Notcharging"|"Charging") icon=" " ;;
        "Discharging")            icon="" ;;
        *)                        icon="" ;;
    esac

    printf '%s %s %s' "$color" "$icon" "$percentage%"
}

cpu() {
    cpu=$(mpstat 1 1 | sed '$!d' | awk '{print $3}')

    case "$(printf '%.f' "$cpu")" in
        [0-9]|1[0-9])         color="$(colors 7)" ;;
        2[0-9]|3[0-9]|4[0-9]) color="$(colors 2)" ;;
        5[0-9]|6[0-9])        color="$(colors 4)" ;;
        7[0-9]|8[0-9])        color="$(colors 3)" ;;
        *)                    color="$(colors 1)" ;;
    esac

    printf '%s %s %s' "$color" "" "$cpu%"
}

datee() {
    printf '%s %s %s' "$(colors 7)" "" "$(date '+%Y-%m-%d')"
}

disk() {
    color=$(colors 7)
    disk=$(df -h -P "$HOME" | sed '$!d' | awk '{print $4}')

    printf '%s %s %s' "$color" "" "$disk"
}

mediaplayer() {
    player="${BLOCK_INSTANCE:-spotifyd}"
    args="--player=$player"
    message="$(playerctl "$args" metadata --format '{{ artist }} - {{ title }}')"

    case "$BLOCK_BUTTON" in
        1) playerctl "$args" previous ;;
        2) playerctl "$args" play-pause ;;
        3) playerctl "$args" next ;;
    esac

    [ -z "$message" ] && return
    [ -z "$DWM" ] && message="$(printf '%s' "$message" | sed -e 's/\&/&amp;/g')"

    printf '%s %s %s' "#2edb59" "" "$message"
}

memory() {
    memory=$(free | sed -ne '/^Mem:\(.*\)/p')
    total=$(printf '%s' "$memory" | awk '{print $2/1024/1024}')
    free=$(printf '%s' "$memory" | awk '{print ($4+$6)/1024/1024}')
    used=$(printf '%s\n' "$total - $free" | bc -l)
    percentage=$(printf '%s\n' "$used / $total * 100" | bc -l)

    case "$percentage" in
        [0-9]|1[0-9])         color="$(colors 1)" ;;
        2[0-9]|3[0-9]|4[0-9]) color="$(colors 3)" ;;
        5[0-9]|6[0-9])        color="$(colors 4)" ;;
        7[0-9]|8[0-9])        color="$(colors 2)" ;;
        *)                    color="$(colors 7)" ;;
    esac

    printf '%s %s %.f%%' "$color" "" "$percentage"
}

timee() {
    printf '%s %s %s' "$(colors 6)" "" "$(date '+%H:%M')"
}

updates() {
    case "$BLOCK_BUTTON" in
        1) updates "$@"; return ;;
    esac

    aur="${1:-true}"
    silent="${2:-false}"
    temp="$(mktemp -d)"
    chmod +x "$temp"
    sudo pacman -Sy --dbpath "$temp" --logfile /dev/null > /dev/null
    updates=$(pacman -Qu 2> /dev/null | grep -cv '\[.*\]')
    [ "$aur" = "true" ] && \
        updates=$(( updates + $(yay -Qua | wc -l) ))

    if [ "$updates" -gt 0 ]; then
        color=$(colors 2)
        message="$updates update(s)"
    elif [ "$silent" != false ]; then
        color=$(colors 3)
        message="sys up to date"
    fi

    [ -n "$color" ] && [ -n "$message" ] && printf '%s %s %s' "$color" "" "$message"
}

volume() {
    mixer="default"
    step="${1:-5%}"
    control="$(amixer -D $mixer scontrols \
        | sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p; 1q")"
    capture="$(amixer -D $mixer get "$control" \
        | sed -n 's/ \+Capabilities:.*volume.*/Capture/p')"
    dat="$(amixer -D $mixer get "$ctl" "$capture" | sed '$!d')"
    volume="$(printf '%s' "$dat" | awk '{print $5}' | sed -e 's/\[\(.*\)\%\]/\1/')"
    status="$(printf '%s' "$dat" | awk '{print $6}' | sed -e 's/\[\(.*\)\]/\1/')"

    [ "$status" = "off" ] && volume=0
    case "$BLOCK_BUTTON" in
        3) notify-send "$mixer $ctl" ; amixer -q -D $mixer sset "$ctl" toggle ;;
        4) amixer -q -D $mixer sset "$ctl" "${step}+" unmute ;;
        5) amixer -q -D $mixer sset "$ctl" "${step}-" unmute ;;
    esac
    case "$volume" in
        0)                    icon="" ;;
        [0-9]|1[0-9])         icon="" ;;
        2[0-9]|3[0-9])        icon="" ;;
        4[0-9]|5[0-9])        icon="" ;;
        6[0-9]|7[0-9]|8[0-9]) icon="" ;;
        *)                    icon="" ;;
    esac

    color=$(colors 7)
    printf '%s %s %s' "$color" "$icon" "$volume%"
}

wifi() {
    interface="${BLOCK_INSTANCE:-wlan0}"
    [ ! -d "/sys/class/net/${interface}/wireless" ] ||
        [ "$(cat /sys/class/net/"$interface"/operstate)" = 'down' ] && return 1
    quality="$(grep "$interface" /proc/net/wireless | awk '{print int($3 * 100 / 70)}')"

    case "$quality" in
        [0-9]|1[0-9])         color=$(colors 1); icon="" ;;
        2[0-9]|3[0-9])        color=$(colors 3); icon="" ;;
        4[0-9]|5[0-9])        color=$(colors 4); icon="" ;;
        6[0-9]|7[0-9]|8[0-9]) color=$(colors 2); icon="" ;;
        *)                    color=$(colors 7); icon="" ;;
    esac

    printf '%s %s %s%%' "$color" "$icon" "$quality"
}
