#!/usr/bin/env sh
#
# Script to nuke docker containers and volumes.
#

# shellcheck disable=SC2046
docker container stop $(docker container ps -aq)
docker container rm $(docker container ps -aq)
docker volume rm $(docker volume ls -q)
docker system prune --all --force
docker volume prune --force
