#!/usr/bin/env sh
#
# Script to execute programs for dwm.
#

# shellcheck disable=SC1090
(scs && feh --no-fehbg --bg-fill ~/Pictures/walls/alt.*) &
dwmblocks &
sxhkd &
# idl &
dunst &
unclutter --jitter 10 --timeout 1 &

# program for both desktop & laptop
firefox-developer-edition &
# st -n nnnterm -e nnn -CHde &
st -n tmuxterm -e tmux -2 &

if [ "$TOP_TYPE" = "laptop" ]; then
    # programs only for laptop
    touchegg &
    st -n rtorrentterm -e rtorrent &
    st -n sptterm -e spt &
    if [ "$(date '+%u')" -le 5 ]; then
        intellij-idea-ultimate-edition &
        slack &
    fi
else
    # programs only for desktop
    qbittorrent &
fi
