#!/usr/bin/env sh
#
# Script to setup the monitor configuration.
#

# shellcheck source=/dev/null

if [ -z "$WAYLAND_DISPLAY" ]; then
    scr="$(xrandr | grep -c ' connected')"
    if [ "$scr" -eq 3 ]; then
        . ~/.local/scripts/mss > /dev/null
    elif [ "$scr" -eq 2 ]; then
        . ~/.local/scripts/wss > /dev/null
    else
        . ~/.local/scripts/sss > /dev/null
    fi
fi
