#!/usr/bin/env sh
#
# Script to setup the single monitor configuration.
#

if [ "$TOP_TYPE" = "laptop" ]; then
    xrandr --output eDP1 --primary --mode 1920x1200 --pos 0x0 --rotate normal \
        --output DP2 --off \
        --output DP3 --off
else
    if [ "$WM" = "sowm" ]; then
        xrandr --output DisplayPort-0 --off \
            --output DisplayPort-2 --off \
            --output DisplayPort-1 --mode 1920x1080 --pos 0x0 --rotate normal \
            --output HDMI-A-0 --mode 1920x1080 --pos 0x0 --rotate normal
    else
        # shellcheck source=/dev/null
        . ~/.local/scripts/mss
    fi
fi
